### ISSUE TITLE
Scraper status and scraper code no longer available

### ISSUE THREAD

**Issue by mikemoate** [alephdata/opensanctions#14]
None of the links in the Developer sections for each data source listed at https://www.opensanctions.org are currently working.

The GitHub links all take you to repositories that were in the https://github.com/opensanctions/ organisation, and this seems to have been removed/closed (404)?

The scraper links all take you to scrapers under https://morph.io/opensanctions/ which now shows as having no scrapers?

When we first started looking at this project (with a view to using and contributing) all these links worked, and it was very easy to audit how the data was being collected/produced (open source code), and how up to date it was (scraper logs and status). Without this level of transparency, we're back to relying on commercial vendors.

**Comment by pudo** [comment]
Yeah, we moved it yesterday and the whole thing isn't totally patched up yet. We're trying to make sure the actual scrapers are fully functional, and that they upload to somewhere public again (e.g. archive.org). When that's active, fixing up the home page should be simple. 

Are you dependent on the data feed? Interested in helping?

**Comment by mikemoate** [comment]
We're not dependant on the feed yet, only stumbled across the project a week ago.

We were researching building our own sanctions checking tooling around the public data sets, building that around the opensanctions data (which is all in the same common format) would obviously be easier. Our main attraction was the level of transparency and audit-ability, with all the scraper code and logs of when and how the data was processed available, that's a significant improvement on any commercial vendor.

What triggered the move, and where will the scrapers run in future? What help do you need?

**Comment by pudo** [comment]
I'd been trying to have it fully transparent on morph.io, but the platform is under-resourced and they kept failing on a daily basis. We're now moving the scrapers to our servers (data.occrp.org) after all, but of course we'll keep both their output and the code base public and accessible.

To this end we also ported it to our scraping toolkit, which should make it easier to run all of them, add new ones, and keep an eye on their status.

In terms of support: we need to check that all of them are working one by one (right now I think one or two of them spew an error, and we need to add a "after run upload to S3 bucket" stage to https://github.com/alephdata/memorious - the scraping framework).

**Comment by pudo** [comment]
See #15, now fixed.
