### ISSUE TITLE
http://opensanctions.org

### ISSUE THREAD

**Issue by thadk** [alephdata/opensanctions#16]
Using my DNS, I cannot access http://opensanctions.org (as linked in header of project), only http://www.opensanctions.org

![image](https://user-images.githubusercontent.com/283343/39555509-cce9e520-4e47-11e8-8301-6f0322494ebe.png)

**Comment by pudo** [comment]
I can't seem to reproduce this. Can anyone else?

**Comment by pudo** [comment]
Ok, good :)
