### ISSUE TITLE
data issue in the Every Politician

### ISSUE THREAD

**Issue by gleeshift** [alephdata/opensanctions#29]
we tried to load the Every Politician file.
1. There are lots of duplicate ids in the file. should value in the Id column be unique?
2. The encode look not right:  we see some data like below. please help. 
,2018-04-26 11:02:14.349715,,2017-08-29,,everypolitician.c99867d6-0f9f-46a8-b4dc-919631e34fca,,,everypolitician,Majles,individual,Ø¬Ø¨Ù‡Ù‡ Ù…ØªØ­Ø¯ØŒ Ø¬Ø¨Ù‡Ù‡ Ù¾Ø§ÛŒØ¯Ø§Ø±ÛŒ Ùˆ Ø¬Ø¨Ù‡Ù‡ Ø§ÛŒØ³ØªØ§Ø¯Ú¯ÛŒ (Ø§ØµÙˆÙ„Ú¯Ø±Ø§),,Ø³ÛŒØ¯ Ø±Ø§Ø¶ÛŒ Ù†ÙˆØ±ÛŒ,,,,,2018-04-12 09:02:55.533419
,2018-04-26 11:02:14.669502,,2017-08-29,,everypolitician.78b2a043-85fe-429b-b3fd-1f05c6041f60,,,everypolitician,Majles,individual,**_**Ø¬Ø¨Ù‡Ù‡ Ù¾Ø§ÛŒØ¯Ø§Ø±ÛŒ,,Ø¹Ù„ÛŒ**_** Ú©Ø§Ø¦ÛŒØ¯ÛŒ,,,,,2018-04-12 09:03:30.146393
,2018-04-26 11:01:12.934513,,2018-03-15,,everypolitician.f9e86a33-873c-4ebf-9e72-ca04ab71d987,,,everypolitician,Hellenic Parliament,individual,INDEPENDENT,,Galinos Spyridon (Spyros),,male,,,2018-04-19 09:36:00.300698

**Comment by pudo** [comment]
This is fixed in the new version.
