### ISSUE TITLE
error building docker image 

### ISSUE THREAD

**Issue by aplekhov** [alephdata/opensanctions#31]
Hi, I'm having trouble building the docker image.  It's failing with the following PIP error when collecting pandas:
```
ModuleNotFoundError: No module named 'numpy'
```

Also, are the csvs files on opensanctions.org no longer being updated?  What's the best current way to to get the data?

Thanks.

**Comment by alexmojaki** [comment]
I got some guidance and an update on https://alephdata.slack.com:

> At the moment, OpenSanctions is in embarrassing state of disarray, and we just haven’t had the time to fix it up a little, which shouldn’t be super hard.
> 
> We used it for a while to prototype some tools, that’s why it’s in a somewhat weird state. These tools are now much more mature, we just need to backport them into OpenSanctions.
> 
> The original idea was for OS to emit the types of entities we deal with in the rest of the Aleph toolchain
> 
> But when we converted the crawlers to that, we didn’t have a backend to store these entities
> 
> There’s now `balkhash`, doing exactly that.
>
> The project is definitely not forgotten, just been super busy on other ends

With help I made some contributions which are somewhat allowing me to create the CSVs on my own. See the updated README.

**Comment by pudo** [comment]
Fixed.
