### ISSUE TITLE
Data not up to date?

### ISSUE THREAD

**Issue by jmootoosamy** [alephdata/opensanctions#33]
Hello,

It seems the data files have not been updated since May 2018. Is there an alternate repository to get the latest data?

https://archive.org/download/opensanctions

Thanks,

**Comment by pantonis** [comment]
@jmootoosamy Did you find a solution to this?

**Comment by pudo** [comment]
Updated (nightly) data is now available again, here: https://docs.alephdata.org/data-commons/sanctions - this is still somewhat work in progress (three crawlers are broken), but it would also be lovely to see some contributions from the community in terms of seeing it extended.
