### ISSUE TITLE
Installation Error Microsoft Visual C++ 14.0 is required. 

### ISSUE THREAD

**Issue by KelumPerera** [alephdata/opensanctions#34]
I'm getting following error when installing.
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

I'm using a windows 10 OS, and Python 3.6.4

Appreciate if someone can help for this. 

[New Text Document (2).txt](https://github.com/alephdata/opensanctions/files/3172847/New.Text.Document.2.txt)

**Comment by pudo** [comment]
I'd strongly recommend you run this on a linux-like system or inside Docker (which works well on Windows). I don't have access to a Windows machine, so I cannot give you much support, unfortunately.
