### ISSUE TITLE
ca_dfatd_sema_sanctions list missing data

### ISSUE THREAD

**Issue by zodiac1214** [alephdata/opensanctions#49]
http://www.international.gc.ca/sanctions/assets/office_docs/sema-lmes.xml has 797 persons for example. However, we only return 19 persons in this project?

**Comment by zodiac1214** [comment]
names = node.findtext('.//Aliases') 
if names is None: 
  return

**Comment by sunu** [comment]
Thanks for reporting. Fixed in https://github.com/alephdata/opensanctions/commit/1849950cb9578ee6e6ded7beea51e9de3fda14d3
