### ISSUE TITLE
Tabular Data Package (the CSV)

### ISSUE THREAD

**Issue by rufuspollock** [alephdata/opensanctions#5]
you've got nice CSV either here #4 or on archive.pudo.org - why not data package?

**Comment by pudo** [comment]
Good point. I started [generating some JSON](http://archive.pudo.org/opennames/latest/metadata.json) to drive the web site but didn't end up using it + there's the [schema for PEPs](https://github.com/pudo/opennames/blob/master/pepparser/schema/entity.json) which gives column titles etc. Should make that into a data package.

**Comment by rgrp** [comment]
+1 :-)

**Comment by rufuspollock** [comment]
@pudo did you get to do this?
