### ISSUE TITLE
us_ofac.py error

### ISSUE THREAD

**Issue by swha03** [alephdata/opensanctions#50]
I found two errors. us_ofac three months us_ofac.py has been modified.
One problem is that there is no Vessel Owner in the Dictionary of REGISTRATIONS.
Another problem is the None type problem.
If len(attr): code indicates an error because attr is NoneType.
(ex.     "UN/LOCODE": (None, 'LegalEntity'),
           "MICEX Code": (None, 'Company'),
           "Digital Currency Address - XBT": (None, 'LegalEntity'))
I just fixed it to if attr:

**Comment by pudo** [comment]
Would you consider submitting a PR to fix this?

**Comment by swha03** [comment]
Okay

**Comment by pudo** [comment]
Re-wrote the parser. We're skipping these specific attributes for the moment, as they don't have a specific equivalent in FtM.
