### ISSUE TITLE
Missing "entity" from sanction and "holder" from passport

### ISSUE THREAD

**Issue by Klem** [alephdata/opensanctions#52]
Hi

I noticed that the field "entity" that allow the linking of a an entity to a sanction is now missing.
Same goes for the "holder" field, that link a person to a passport, and the organisation/owner

Is this a bug? Otherwise, does that mean the the link between these entities in now broken for some reason?

Thanx

Before
![image](https://user-images.githubusercontent.com/688235/75156857-4a412580-5713-11ea-9b96-fb702530d64c.png)

After
![image](https://user-images.githubusercontent.com/688235/75156920-6644c700-5713-11ea-9aa0-65879fc68674.png)

**Comment by pudo** [comment]
I've fixed the underlying software bug, the IDs should be back after the exporter next runs (in the next 24-48 hours).

**Comment by Klem** [comment]
Thanx a lot!
