### ISSUE TITLE
EU EEAS Sanctions Change

### ISSUE THREAD

**Issue by daviddiazvico** [alephdata/opensanctions#54]
It seems the EU EEAS Sanctions list has been moved from
http://ec.europa.eu/external_relations/cfsp/sanctions/list/version4/global/global.xml
to
https://data.europa.eu/euodp/es/data/dataset/consolidated-list-of-persons-groups-and-entities-subject-to-eu-financial-sanctions

The list in the old URL has not been updated in the last months. Also, the XML file structure has been modified.

**Comment by sunu** [comment]
Thanks for the report @daviddiazvico! I'll take a look and update the crawler soon.
