### ISSUE TITLE
Aleph aggregator problem

### ISSUE THREAD

**Issue by oliba723** [alephdata/opensanctions#55]
the ftm_load_aleph method was not working (ftm_store version 2.2.3) until I changed the aggregator method from:

aggregator:
  method: ftm_load_aleph

to:

aggregator:
  method: ftmstore.memorious:ftm_load_aleph

since the aggregator-method in memorious/logic/crawler.py expects a colon:

```
memorious/logic/crawler.py 
    @property
    def aggregator_method(self):
        if self.aggregator_config:
            method = self.aggregator_config.get("method")
            if not method:
                return
            if ':' in method:
                package, method = method.rsplit(':', 1)
                module = import_module(package)
                return getattr(module, method)
```

Or is there something else I missed in the setup?

**Comment by sunu** [comment]
Hi @oliba723, this should be fixed now by the new release of Memorious (version 1.8.3)
