### ISSUE TITLE
What are the `ALEPHCLIENT_HOST` and `ALEPHCLIENT_API_KEY`?

### ISSUE THREAD

**Issue by haarts** [alephdata/opensanctions#57]
I would like to push result of the scrapers to Aleph. How ever I do not know what the values of the variables `ALEPHCLIENT_API_KEY` and `ALEPHCLIENT_HOST` should be. 

Is the `ALEPHCLIENT_API_KEY` the same as the `ALEPH_SECRET_KEY` as set in the `aleph.env` (from [here](https://github.com/alephdata/aleph/))? 

And where should `ALEPHCLIENT_HOST` point to? I'm running both Aleph and Opensanctions in their respective docker environments.

**Comment by pudo** [comment]
These two variables should describe how memorious uploads data to aleph. Memorious acts as a generic API client, so it needs some sort of host name or IP address (e.g. the IP of the server if the Aleph API is exposed on it). The API Key needs to be for a user (you can see your API Key in your settings), not the global ALEPH_SECRET. I'd recommend making a dedicated memorious user on the Aleph instance via the `createuser` command.

**Comment by haarts** [comment]
Alright. I'll get busy tying the two dockers together network wise and I found the relevant `createuser` [docs](https://docs.alephdata.org/developers/technical-faq/look-ma-no-docker#aleph-configuration). Thanks for the help!
