### ISSUE TITLE
Add an crawler for Financial Sanctions Files (FSF) published by EU Commision

### ISSUE THREAD

**Issue by thimios** [alephdata/opensanctions#61]
I have created a PR here: https://github.com/alephdata/opensanctions/pull/60

@pudo @sunu Is this a useful contribution? Could you please give a review?

**Comment by sunu** [comment]
Hi @thimios, thanks for writing the crawler. It definitely is useful. I just have one question for some clarification. In the eu_eeas_sanctions crawler we scrape consolidated sanctions from https://data.europa.eu/euodp/en/data/dataset/consolidated-list-of-persons-groups-and-entities-subject-to-eu-financial-sanctions. Is there a chance the FSF sanctions are a subset of that?

**Comment by pudo** [comment]
Yep, it's the same this as our old `eu_eeas_sanctions` but parsing it from the newer source.
