### ISSUE TITLE
EU EEAS Sanctions seems to be moved behind a login

### ISSUE THREAD

**Issue by ChrisjanWust** [alephdata/opensanctions#72]
The current url specified in the EU EEAS Sanctions config file, [https://data.europa.eu/euodp/es/data/dataset/consolidated-list-of-persons-groups-and-entities-subject-to-eu-financial-sanctions](https://data.europa.eu/euodp/es/data/dataset/consolidated-list-of-persons-groups-and-entities-subject-to-eu-financial-sanctions), is no longer available, returning a 404. It seems the datasets have been moved behind a login, as per [https://eeas.europa.eu/headquarters/headquarters-homepage_en/8442/Consolidated%20list%20of%20sanctions](https://eeas.europa.eu/headquarters/headquarters-homepage_en/8442/Consolidated%20list%20of%20sanctions).

**Comment by ChrisjanWust** [comment]
The EU Open Data Portal has restored the old data location of the EU EEAS Sanctions, with a deprecated flag. The scraper is running successfully, but unsure how long the data will remain there.

**Comment by pudo** [comment]
FWIW here's a link to the new version with my personal authentication token. The fact that my API key coincides with my name is probably a pure accident, because the EC could not possibly... 

https://webgate.ec.europa.eu/fsd/fsf/public/files/xmlFullSanctionsList_1_1/content?token=nlinfrie

**Comment by oddobert** [comment]
In the new URL you can either get the XML or a CSV, has anyone made a new crawler? 
I am considering making one myself, however I am just atrting out with opernsanctions and I am likely going to spend considerable time understanding the API.

**Comment by pudo** [comment]
I'm torn between a bottle of wine and doing the EU parser for the XML version tonight... But if you're gonna make a PR, let me know and the wine gets it :)

**Comment by pudo** [comment]
I merged #60, which provides a really good starting point for this (and also resolves this issue)
