### ISSUE TITLE
CIA World Leaders site overhauled

### ISSUE THREAD

**Issue by ChrisjanWust** [alephdata/opensanctions#73]
CIA has redone their site. The current specified in the CIA World Leaders scraper config, [https://www.cia.gov/library/publications/resources/world-leaders-1/index.html](https://www.cia.gov/library/publications/resources/world-leaders-1/index.html), returns a 404. The lists now reside at [https://www.cia.gov/resources/world-leaders/foreign-governments/](https://www.cia.gov/resources/world-leaders/foreign-governments/).

**Comment by pudo** [comment]
OK, this is a complete overhaul of the scraper, I guess. Are you up for giving it a shot, @ChrisjanWust?
